id = "dang"
name = "Dang"
version = "0.1.1"
schema_version = 1
description = "Dang language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/dang"

[grammars.dang]
repository = "https://github.com/vito/dang"
commit = "c7540caedab9cc66f171339dcafef675003b1338"
path = "treesitter"

[language_servers.dang-lsp]
name = "Dang LSP"
languages = ["Dang"]
