id = "dang"
name = "Dang"
version = "0.1.1"
schema_version = 1
description = "Dang language support for Zed"
authors = ["vito"]
repository = "https://github.com/vito/dang"

[grammars.dang]
repository = "https://github.com/vito/dang"
commit = "9de76eecf6777f362a7e194351564e9cf78520b7"
path = "treesitter"

[language_servers.dang-lsp]
name = "Dang LSP"
languages = ["Dang"]
